unzip_pret_data:
  data_path: data/pre-training/raw_3d_audio
  data_work_path: data/pre-training/raw_3d_audio_data

pret_dataset:
  save_path: data/pre-training/pret_l3das22_raw_ts4_str4

ft_dataset_tau2019:
  manifest_folder: data/fine-tuning/manifest/finetuning

ft_dataset_tau2020:
  manifest_folder: data/fine-tuning/manifest/finetuning