unzip_pret_data:
  data_path: data/pre-training/raw_3d_audio
  data_work_path: data/pre-training/raw_3d_audio_data

pret_dataset:
  l3das: 21
  data_work_path: /work/olima/raw_3d_audio_data
  save_path: /work/olima/pret_l3das21_raw
  fs_target: 16000
  window_in_s: 10
  stride_in_s: 4

ft_dataset_tau2019:
  save_folder: data/fine-tuning/TAU_2019
  manifest_folder: data/fine-tuning/manifest/finetuning
  metadata_dev_path: data/pre-training/raw_3d_audio_data/TAU_2019/metadata_dev
  metadata_eval_path: data/pre-training/raw_3d_audio_data/TAU_2019/metadata_eval
  foa_dev_path: data/pre-training/raw_3d_audio_data/TAU_2019/foa_dev
  foa_eval_path: data/pre-training/raw_3d_audio_data/TAU_2019/proj/asignal/DCASE2019/dataset/foa_eval
  window_in_s: 2.97
  stride_in_s: 0.625
  